CREATE ROLE RO_LUMIN_APP;   
CREATE ROLE RO_LUMIN_ADMIN;

GRANT CREATE SESSION TO RO_LUMIN_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON APP_USER TO RO_LUMIN_APP;
GRANT SELECT, INSERT, UPDATE ON PRACTICE_ATTEMPT TO RO_LUMIN_APP;
GRANT EXECUTE ON PKG_ACCOUNT TO RO_LUMIN_APP;
GRANT EXECUTE ON PKG_PROGRESS TO RO_LUMIN_APP;
GRANT EXECUTE ON PKG_auth TO RO_LUMIN_APP;

GRANT ALL PRIVILEGES TO RO_LUMIN_ADMIN;

CREATE USER LUMIN_BACKEND IDENTIFIED BY "LuminBackend" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
CREATE USER LUMIN_DBA IDENTIFIED BY "LuminAdmin" DEFAULT TABLESPACE USERS;

GRANT RO_LUMIN_APP TO LUMIN_BACKEND;
GRANT RO_LUMIN_ADMIN TO LUMIN_DBA;